# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 02:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardaStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('blank', models.CharField(max_length=80)),
                ('Sun', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=80)),
                ('Longitude', models.CharField(max_length=80)),
                ('Latitude', models.CharField(max_length=80)),
                ('County', models.CharField(max_length=80)),
                ('Phone', models.CharField(max_length=80)),
                ('StationID', models.CharField(max_length=80)),
                ('Station', models.CharField(max_length=80)),
                ('Mon_Fri', models.CharField(max_length=80)),
                ('Sat', models.CharField(max_length=80)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
